/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as SafetyValidatorRouteImport } from './routes/safety-validator'
import { Route as MissionReviewRouteImport } from './routes/mission-review'
import { Route as MissionOutputRouteImport } from './routes/mission-output'
import { Route as MissionGeneratorRouteImport } from './routes/mission-generator'
import { Route as FieldMapRouteImport } from './routes/field-map'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ChallengeFitRouteImport } from './routes/challenge-fit'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyValidatorRoute = SafetyValidatorRouteImport.update({
  id: '/safety-validator',
  path: '/safety-validator',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionReviewRoute = MissionReviewRouteImport.update({
  id: '/mission-review',
  path: '/mission-review',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionOutputRoute = MissionOutputRouteImport.update({
  id: '/mission-output',
  path: '/mission-output',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionGeneratorRoute = MissionGeneratorRouteImport.update({
  id: '/mission-generator',
  path: '/mission-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldMapRoute = FieldMapRouteImport.update({
  id: '/field-map',
  path: '/field-map',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeFitRoute = ChallengeFitRouteImport.update({
  id: '/challenge-fit',
  path: '/challenge-fit',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/challenge-fit': typeof ChallengeFitRoute
  '/demo': typeof DemoRoute
  '/field-map': typeof FieldMapRoute
  '/mission-generator': typeof MissionGeneratorRoute
  '/mission-output': typeof MissionOutputRoute
  '/mission-review': typeof MissionReviewRoute
  '/safety-validator': typeof SafetyValidatorRoute
  '/scenarios': typeof ScenariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/challenge-fit': typeof ChallengeFitRoute
  '/demo': typeof DemoRoute
  '/field-map': typeof FieldMapRoute
  '/mission-generator': typeof MissionGeneratorRoute
  '/mission-output': typeof MissionOutputRoute
  '/mission-review': typeof MissionReviewRoute
  '/safety-validator': typeof SafetyValidatorRoute
  '/scenarios': typeof ScenariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/challenge-fit': typeof ChallengeFitRoute
  '/demo': typeof DemoRoute
  '/field-map': typeof FieldMapRoute
  '/mission-generator': typeof MissionGeneratorRoute
  '/mission-output': typeof MissionOutputRoute
  '/mission-review': typeof MissionReviewRoute
  '/safety-validator': typeof SafetyValidatorRoute
  '/scenarios': typeof ScenariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/challenge-fit'
    | '/demo'
    | '/field-map'
    | '/mission-generator'
    | '/mission-output'
    | '/mission-review'
    | '/safety-validator'
    | '/scenarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/challenge-fit'
    | '/demo'
    | '/field-map'
    | '/mission-generator'
    | '/mission-output'
    | '/mission-review'
    | '/safety-validator'
    | '/scenarios'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/challenge-fit'
    | '/demo'
    | '/field-map'
    | '/mission-generator'
    | '/mission-output'
    | '/mission-review'
    | '/safety-validator'
    | '/scenarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChallengeFitRoute: typeof ChallengeFitRoute
  DemoRoute: typeof DemoRoute
  FieldMapRoute: typeof FieldMapRoute
  MissionGeneratorRoute: typeof MissionGeneratorRoute
  MissionOutputRoute: typeof MissionOutputRoute
  MissionReviewRoute: typeof MissionReviewRoute
  SafetyValidatorRoute: typeof SafetyValidatorRoute
  ScenariosRoute: typeof ScenariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety-validator': {
      id: '/safety-validator'
      path: '/safety-validator'
      fullPath: '/safety-validator'
      preLoaderRoute: typeof SafetyValidatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-review': {
      id: '/mission-review'
      path: '/mission-review'
      fullPath: '/mission-review'
      preLoaderRoute: typeof MissionReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-output': {
      id: '/mission-output'
      path: '/mission-output'
      fullPath: '/mission-output'
      preLoaderRoute: typeof MissionOutputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-generator': {
      id: '/mission-generator'
      path: '/mission-generator'
      fullPath: '/mission-generator'
      preLoaderRoute: typeof MissionGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-map': {
      id: '/field-map'
      path: '/field-map'
      fullPath: '/field-map'
      preLoaderRoute: typeof FieldMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge-fit': {
      id: '/challenge-fit'
      path: '/challenge-fit'
      fullPath: '/challenge-fit'
      preLoaderRoute: typeof ChallengeFitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChallengeFitRoute: ChallengeFitRoute,
  DemoRoute: DemoRoute,
  FieldMapRoute: FieldMapRoute,
  MissionGeneratorRoute: MissionGeneratorRoute,
  MissionOutputRoute: MissionOutputRoute,
  MissionReviewRoute: MissionReviewRoute,
  SafetyValidatorRoute: SafetyValidatorRoute,
  ScenariosRoute: ScenariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
